 pipeline{
            agent any
            
            tools {
              maven 'maven-3.5.4'
              jdk 'jdk1.8.0_181'
            }
            
             stages {
                stage('initialize') {
                    steps {
                        sh '''
                           echo "PATH = ${PATH}"
                           echo "M2_HOME = ${M2_HOME}"
                           echo "JAVA_HOME = ${JAVA_HOME}"
                        '''
                    }
                }
                stage('first') {
                    steps {
                        
                     echo 'first stage'
                     script {
                         for (int i = 0; i < 5; i++) {
                             echo "Printing number ${i}"
                         }
                     }
                    }
                }
            }
            
            post {
                always {
                    echo "Pipeline executed"
                }
    }
}