node('master') {

 try {
    stage("echo") {
        sh 'echo "Hello World!"'
        def obj = null
        sh "${obj.class}"
    }
  }catch (Exception e) {
      error 'broken pipeline '+e
      currentBuild.result='FAILURE'
  } finally {
      stage('send notification email') {
          //mail bcc: '', body: 'something is wrong with ${env.BUILD_URL}', cc: '', from: 'jenkins.home.amd@gmail.com', replyTo: '', subject: 'Failed pipeline: ${currentBuild.fullDisplayName}', to: 'thanuj.kumar@gmail.com'
          notifyException()
      }
  }
}

def notifyException() {
     emailext (
      subject: "EXCEPTION: Job '${env.JOB_NAME} [${env.BUILD_NUMBER}]'",
      body: """<p>EXCEPTION: Job '${env.JOB_NAME} [${env.BUILD_NUMBER}]':</p>
        <p>Check console output at &QUOT;<a href='${env.BUILD_URL}'>${env.JOB_NAME} [${env.BUILD_NUMBER}]</a>&QUOT;</p>""",
      to: 'jenkins.home.amd@gmail.com'
    )

}