node('master') { ////To point to specific jenkins labeled node
   
   stage('Checkout') { // for display purposes
      // Get some code from a GitHub repository
      git 'https://github.com/thanujkumar/bean-validation2.git'
   }
   stage('Package') {
      // Run the maven build
      if (isUnix()) {
         sh "mvn -Dmaven.test.failure.ignore clean package"
      } else {
         bat(/mvn -Dmaven.test.failure.ignore clean package/)
      }
   }
   stage('Results') {
      junit '**/*/target/surefire-reports/*.xml'
      archive 'target/*.jar'
   }
}
 